kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readsb-autogain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readsb-collectd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi